SC-143  Adds permission for the login app' to add session tags
Sage-Bionetworks/synapse-login-aws-infra pull request #32
Opened 2020-05-16 23:16 UTC by brucehoff

To support an upcoming change to scipool-login in which the app' will add session tags, this change to the deployment script adds the permission to add session tags.  This change is based on 
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html#id_session-tags_permissions-required
which says, "you must have the following permissions-only action in your policy: sts:TagSession"

2020-05-18 15:29 UTC, zaro0508 requested changes

2020-05-18 15:29 UTC, zaro0508 commented on templates/app.yaml
> +              - 'sts:TagSession'
you don't need another list item. Just remove this item and move - 'sts:TagSession' under - 'sts:AssumeRole'

2020-05-18 15:29 UTC, zaro0508 commented on templates/app.yaml
>                - 'sts:AssumeRole'
```suggestion
              - 'sts:AssumeRole'
              - 'sts:TagSession'
```

2020-05-18 15:34 UTC, brucehoff commented on templates/app.yaml
> +              - 'sts:TagSession'
Thank you for the suggestion.  I have updated the PR.

2020-05-18 17:59 UTC, zaro0508 approved these changes

2020-05-20 01:49 UTC, xschildw approved these changes

2020-05-20 01:49 UTC, merged